# Generated by Django 2.2.6 on 2020-03-11 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=100)),
                ('block_code', models.CharField(max_length=10)),
                ('doc', models.DateTimeField()),
                ('dom', models.DateTimeField()),
                ('block_status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=100)),
                ('center_code', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('doc', models.DateTimeField()),
                ('dom', models.DateTimeField()),
                ('desc', models.TextField()),
                ('center_status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10)),
                ('doc', models.DateTimeField()),
                ('dom', models.DateTimeField()),
                ('course_status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=10)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.Center')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=10)),
                ('floor_no', models.CharField(choices=[('0', 'Ground Floor'), ('1', 'First Floor'), ('2', 'Second Floor'), ('3', 'Third Floor')], max_length=10)),
                ('capacity', models.IntegerField()),
                ('doc', models.DateTimeField()),
                ('dom', models.DateTimeField()),
                ('room_status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=10)),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.Block')),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.Center')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10)),
                ('doc', models.DateTimeField()),
                ('dom', models.DateTimeField()),
                ('state_status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('doc', models.DateTimeField()),
                ('teacher_status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=200)),
                ('doc', models.DateTimeField()),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.Course')),
            ],
        ),
        migrations.CreateModel(
            name='SeatingArrangement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.Center')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.Course')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.Room')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=100)),
                ('dep_code', models.CharField(max_length=10, null=True)),
                ('doc', models.DateTimeField()),
                ('dom', models.DateTimeField()),
                ('dep_status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.Course')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=10)),
                ('doc', models.DateTimeField()),
                ('dom', models.DateTimeField()),
                ('city_status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], max_length=10)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.State')),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.City'),
        ),
        migrations.AddField(
            model_name='block',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examhall.Center'),
        ),
    ]
